services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: keycloak
    command: start-dev -Dkeycloak.profile.feature.upload_scripts=enabled
    env_file:
      - ./keycloak.env
    volumes:
      - ./config/db:/opt/keycloak/data
    ports:
      - 8080:8080

