services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: keycloak
    command: start-dev -Dkeycloak.profile.feature.upload_scripts=enabled -Dkeycloak.theme.cacheThemes=false
    env_file:
      - ./keycloak.env
    volumes:
      - ./config/db:/opt/keycloak/data
      - ./themes/templates:/opt/keycloak/themes
      - ./mfa/plugins:/opt/keycloak/providers
    ports:
      - 8080:8080
  smtp:
    image: rnwood/smtp4dev:v3
    restart: always
    container_name: smtp4dev
    ports:
      - "8081:80"
      - "8025:25"
      - "8143:143"

